// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Method04.proto

package S04Cinema_Admission;

public interface TicketResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cinema2.TicketResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool accepted = 1;</code>
   */
  boolean getAccepted();

  /**
   * <code>string message = 2;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
