// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Method04.proto

package S04Cinema_Admission;

public interface TicketRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cinema2.TicketRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 ticket_number = 1;</code>
   */
  int getTicketNumber();

  /**
   * <code>string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
