// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Method06.proto

package S06Food_Payment;

public interface PaymentRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cinema2.PaymentRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string card_number = 1;</code>
   */
  java.lang.String getCardNumber();
  /**
   * <code>string card_number = 1;</code>
   */
  com.google.protobuf.ByteString
      getCardNumberBytes();

  /**
   * <code>string cardholder = 2;</code>
   */
  java.lang.String getCardholder();
  /**
   * <code>string cardholder = 2;</code>
   */
  com.google.protobuf.ByteString
      getCardholderBytes();

  /**
   * <code>string security_number = 3;</code>
   */
  java.lang.String getSecurityNumber();
  /**
   * <code>string security_number = 3;</code>
   */
  com.google.protobuf.ByteString
      getSecurityNumberBytes();

  /**
   * <code>string issue_date = 4;</code>
   */
  java.lang.String getIssueDate();
  /**
   * <code>string issue_date = 4;</code>
   */
  com.google.protobuf.ByteString
      getIssueDateBytes();
}
