// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Method06.proto

package S06Food_Payment;

/**
 * <pre>
 * Message for sending payment details
 * </pre>
 *
 * Protobuf type {@code cinema2.PaymentRequest}
 */
public  final class PaymentRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:cinema2.PaymentRequest)
    PaymentRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PaymentRequest.newBuilder() to construct.
  private PaymentRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PaymentRequest() {
    cardNumber_ = "";
    cardholder_ = "";
    securityNumber_ = "";
    issueDate_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private PaymentRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            cardNumber_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            cardholder_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            securityNumber_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            issueDate_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return S06Food_Payment.S06FoodPayment_1.internal_static_cinema2_PaymentRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return S06Food_Payment.S06FoodPayment_1.internal_static_cinema2_PaymentRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            S06Food_Payment.PaymentRequest.class, S06Food_Payment.PaymentRequest.Builder.class);
  }

  public static final int CARD_NUMBER_FIELD_NUMBER = 1;
  private volatile java.lang.Object cardNumber_;
  /**
   * <code>string card_number = 1;</code>
   */
  public java.lang.String getCardNumber() {
    java.lang.Object ref = cardNumber_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      cardNumber_ = s;
      return s;
    }
  }
  /**
   * <code>string card_number = 1;</code>
   */
  public com.google.protobuf.ByteString
      getCardNumberBytes() {
    java.lang.Object ref = cardNumber_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      cardNumber_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CARDHOLDER_FIELD_NUMBER = 2;
  private volatile java.lang.Object cardholder_;
  /**
   * <code>string cardholder = 2;</code>
   */
  public java.lang.String getCardholder() {
    java.lang.Object ref = cardholder_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      cardholder_ = s;
      return s;
    }
  }
  /**
   * <code>string cardholder = 2;</code>
   */
  public com.google.protobuf.ByteString
      getCardholderBytes() {
    java.lang.Object ref = cardholder_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      cardholder_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SECURITY_NUMBER_FIELD_NUMBER = 3;
  private volatile java.lang.Object securityNumber_;
  /**
   * <code>string security_number = 3;</code>
   */
  public java.lang.String getSecurityNumber() {
    java.lang.Object ref = securityNumber_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      securityNumber_ = s;
      return s;
    }
  }
  /**
   * <code>string security_number = 3;</code>
   */
  public com.google.protobuf.ByteString
      getSecurityNumberBytes() {
    java.lang.Object ref = securityNumber_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      securityNumber_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ISSUE_DATE_FIELD_NUMBER = 4;
  private volatile java.lang.Object issueDate_;
  /**
   * <code>string issue_date = 4;</code>
   */
  public java.lang.String getIssueDate() {
    java.lang.Object ref = issueDate_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      issueDate_ = s;
      return s;
    }
  }
  /**
   * <code>string issue_date = 4;</code>
   */
  public com.google.protobuf.ByteString
      getIssueDateBytes() {
    java.lang.Object ref = issueDate_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      issueDate_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getCardNumberBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, cardNumber_);
    }
    if (!getCardholderBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, cardholder_);
    }
    if (!getSecurityNumberBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, securityNumber_);
    }
    if (!getIssueDateBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, issueDate_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getCardNumberBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, cardNumber_);
    }
    if (!getCardholderBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, cardholder_);
    }
    if (!getSecurityNumberBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, securityNumber_);
    }
    if (!getIssueDateBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, issueDate_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof S06Food_Payment.PaymentRequest)) {
      return super.equals(obj);
    }
    S06Food_Payment.PaymentRequest other = (S06Food_Payment.PaymentRequest) obj;

    boolean result = true;
    result = result && getCardNumber()
        .equals(other.getCardNumber());
    result = result && getCardholder()
        .equals(other.getCardholder());
    result = result && getSecurityNumber()
        .equals(other.getSecurityNumber());
    result = result && getIssueDate()
        .equals(other.getIssueDate());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CARD_NUMBER_FIELD_NUMBER;
    hash = (53 * hash) + getCardNumber().hashCode();
    hash = (37 * hash) + CARDHOLDER_FIELD_NUMBER;
    hash = (53 * hash) + getCardholder().hashCode();
    hash = (37 * hash) + SECURITY_NUMBER_FIELD_NUMBER;
    hash = (53 * hash) + getSecurityNumber().hashCode();
    hash = (37 * hash) + ISSUE_DATE_FIELD_NUMBER;
    hash = (53 * hash) + getIssueDate().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static S06Food_Payment.PaymentRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static S06Food_Payment.PaymentRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static S06Food_Payment.PaymentRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static S06Food_Payment.PaymentRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static S06Food_Payment.PaymentRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static S06Food_Payment.PaymentRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static S06Food_Payment.PaymentRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static S06Food_Payment.PaymentRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static S06Food_Payment.PaymentRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static S06Food_Payment.PaymentRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static S06Food_Payment.PaymentRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static S06Food_Payment.PaymentRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(S06Food_Payment.PaymentRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Message for sending payment details
   * </pre>
   *
   * Protobuf type {@code cinema2.PaymentRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:cinema2.PaymentRequest)
      S06Food_Payment.PaymentRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return S06Food_Payment.S06FoodPayment_1.internal_static_cinema2_PaymentRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return S06Food_Payment.S06FoodPayment_1.internal_static_cinema2_PaymentRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              S06Food_Payment.PaymentRequest.class, S06Food_Payment.PaymentRequest.Builder.class);
    }

    // Construct using S06Food_Payment.PaymentRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      cardNumber_ = "";

      cardholder_ = "";

      securityNumber_ = "";

      issueDate_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return S06Food_Payment.S06FoodPayment_1.internal_static_cinema2_PaymentRequest_descriptor;
    }

    @java.lang.Override
    public S06Food_Payment.PaymentRequest getDefaultInstanceForType() {
      return S06Food_Payment.PaymentRequest.getDefaultInstance();
    }

    @java.lang.Override
    public S06Food_Payment.PaymentRequest build() {
      S06Food_Payment.PaymentRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public S06Food_Payment.PaymentRequest buildPartial() {
      S06Food_Payment.PaymentRequest result = new S06Food_Payment.PaymentRequest(this);
      result.cardNumber_ = cardNumber_;
      result.cardholder_ = cardholder_;
      result.securityNumber_ = securityNumber_;
      result.issueDate_ = issueDate_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof S06Food_Payment.PaymentRequest) {
        return mergeFrom((S06Food_Payment.PaymentRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(S06Food_Payment.PaymentRequest other) {
      if (other == S06Food_Payment.PaymentRequest.getDefaultInstance()) return this;
      if (!other.getCardNumber().isEmpty()) {
        cardNumber_ = other.cardNumber_;
        onChanged();
      }
      if (!other.getCardholder().isEmpty()) {
        cardholder_ = other.cardholder_;
        onChanged();
      }
      if (!other.getSecurityNumber().isEmpty()) {
        securityNumber_ = other.securityNumber_;
        onChanged();
      }
      if (!other.getIssueDate().isEmpty()) {
        issueDate_ = other.issueDate_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      S06Food_Payment.PaymentRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (S06Food_Payment.PaymentRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object cardNumber_ = "";
    /**
     * <code>string card_number = 1;</code>
     */
    public java.lang.String getCardNumber() {
      java.lang.Object ref = cardNumber_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cardNumber_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string card_number = 1;</code>
     */
    public com.google.protobuf.ByteString
        getCardNumberBytes() {
      java.lang.Object ref = cardNumber_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cardNumber_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string card_number = 1;</code>
     */
    public Builder setCardNumber(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      cardNumber_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string card_number = 1;</code>
     */
    public Builder clearCardNumber() {
      
      cardNumber_ = getDefaultInstance().getCardNumber();
      onChanged();
      return this;
    }
    /**
     * <code>string card_number = 1;</code>
     */
    public Builder setCardNumberBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      cardNumber_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object cardholder_ = "";
    /**
     * <code>string cardholder = 2;</code>
     */
    public java.lang.String getCardholder() {
      java.lang.Object ref = cardholder_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cardholder_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string cardholder = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCardholderBytes() {
      java.lang.Object ref = cardholder_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cardholder_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string cardholder = 2;</code>
     */
    public Builder setCardholder(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      cardholder_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string cardholder = 2;</code>
     */
    public Builder clearCardholder() {
      
      cardholder_ = getDefaultInstance().getCardholder();
      onChanged();
      return this;
    }
    /**
     * <code>string cardholder = 2;</code>
     */
    public Builder setCardholderBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      cardholder_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object securityNumber_ = "";
    /**
     * <code>string security_number = 3;</code>
     */
    public java.lang.String getSecurityNumber() {
      java.lang.Object ref = securityNumber_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        securityNumber_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string security_number = 3;</code>
     */
    public com.google.protobuf.ByteString
        getSecurityNumberBytes() {
      java.lang.Object ref = securityNumber_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        securityNumber_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string security_number = 3;</code>
     */
    public Builder setSecurityNumber(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      securityNumber_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string security_number = 3;</code>
     */
    public Builder clearSecurityNumber() {
      
      securityNumber_ = getDefaultInstance().getSecurityNumber();
      onChanged();
      return this;
    }
    /**
     * <code>string security_number = 3;</code>
     */
    public Builder setSecurityNumberBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      securityNumber_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object issueDate_ = "";
    /**
     * <code>string issue_date = 4;</code>
     */
    public java.lang.String getIssueDate() {
      java.lang.Object ref = issueDate_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        issueDate_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string issue_date = 4;</code>
     */
    public com.google.protobuf.ByteString
        getIssueDateBytes() {
      java.lang.Object ref = issueDate_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        issueDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string issue_date = 4;</code>
     */
    public Builder setIssueDate(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      issueDate_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string issue_date = 4;</code>
     */
    public Builder clearIssueDate() {
      
      issueDate_ = getDefaultInstance().getIssueDate();
      onChanged();
      return this;
    }
    /**
     * <code>string issue_date = 4;</code>
     */
    public Builder setIssueDateBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      issueDate_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:cinema2.PaymentRequest)
  }

  // @@protoc_insertion_point(class_scope:cinema2.PaymentRequest)
  private static final S06Food_Payment.PaymentRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new S06Food_Payment.PaymentRequest();
  }

  public static S06Food_Payment.PaymentRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PaymentRequest>
      PARSER = new com.google.protobuf.AbstractParser<PaymentRequest>() {
    @java.lang.Override
    public PaymentRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new PaymentRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<PaymentRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PaymentRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public S06Food_Payment.PaymentRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

