// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Method06.proto

package S06Food_Payment;

public interface PaymentResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cinema2.PaymentResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>string confirmation_number = 2;</code>
   */
  java.lang.String getConfirmationNumber();
  /**
   * <code>string confirmation_number = 2;</code>
   */
  com.google.protobuf.ByteString
      getConfirmationNumberBytes();

  /**
   * <code>string ticket_number = 3;</code>
   */
  java.lang.String getTicketNumber();
  /**
   * <code>string ticket_number = 3;</code>
   */
  com.google.protobuf.ByteString
      getTicketNumberBytes();
}
