// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Method06.proto

package S06Food_Payment;

public final class S06FoodPayment_1 {
  private S06FoodPayment_1() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cinema2_PaymentRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cinema2_PaymentRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cinema2_PaymentResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cinema2_PaymentResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016Method06.proto\022\007cinema2\"f\n\016PaymentRequ" +
      "est\022\023\n\013card_number\030\001 \001(\t\022\022\n\ncardholder\030\002" +
      " \001(\t\022\027\n\017security_number\030\003 \001(\t\022\022\n\nissue_d" +
      "ate\030\004 \001(\t\"V\n\017PaymentResponse\022\017\n\007message\030" +
      "\001 \001(\t\022\033\n\023confirmation_number\030\002 \001(\t\022\025\n\rti" +
      "cket_number\030\003 \001(\t2Y\n\016PaymentService\022G\n\016P" +
      "rocessPayment\022\027.cinema2.PaymentRequest\032\030" +
      ".cinema2.PaymentResponse(\0010\001B%\n\017S06Food_" +
      "PaymentB\020S06FoodPayment_1P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_cinema2_PaymentRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cinema2_PaymentRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cinema2_PaymentRequest_descriptor,
        new java.lang.String[] { "CardNumber", "Cardholder", "SecurityNumber", "IssueDate", });
    internal_static_cinema2_PaymentResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_cinema2_PaymentResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cinema2_PaymentResponse_descriptor,
        new java.lang.String[] { "Message", "ConfirmationNumber", "TicketNumber", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
