// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Method05.proto

package S05Drink_Catalog;

public interface DrinkRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cinema2.DrinkRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * List of drink IDs chosen by the client
   * </pre>
   *
   * <code>repeated int32 drink_ids = 1;</code>
   */
  java.util.List<java.lang.Integer> getDrinkIdsList();
  /**
   * <pre>
   * List of drink IDs chosen by the client
   * </pre>
   *
   * <code>repeated int32 drink_ids = 1;</code>
   */
  int getDrinkIdsCount();
  /**
   * <pre>
   * List of drink IDs chosen by the client
   * </pre>
   *
   * <code>repeated int32 drink_ids = 1;</code>
   */
  int getDrinkIds(int index);
}
