// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Method05.proto

package S05Drink_Catalog;

public interface DrinkResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:artifact_cinema.DrinkResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * ID of the drink
   * </pre>
   *
   * <code>int32 drink_id = 1;</code>
   */
  int getDrinkId();

  /**
   * <pre>
   * Confirmation message about the drink
   * </pre>
   *
   * <code>string confirmation_message = 2;</code>
   */
  java.lang.String getConfirmationMessage();
  /**
   * <pre>
   * Confirmation message about the drink
   * </pre>
   *
   * <code>string confirmation_message = 2;</code>
   */
  com.google.protobuf.ByteString
      getConfirmationMessageBytes();
}
