// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Method05.proto

package S05Drink_Catalog;

public final class S05DrinkCatalog {
  private S05DrinkCatalog() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cinema2_DrinkRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cinema2_DrinkRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cinema2_DrinkResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cinema2_DrinkResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016Method05.proto\022\007cinema2\"!\n\014DrinkReques" +
      "t\022\021\n\tdrink_ids\030\001 \003(\005\"?\n\rDrinkResponse\022\020\n" +
      "\010drink_id\030\001 \001(\005\022\034\n\024confirmation_message\030" +
      "\002 \001(\t2N\n\014DrinkService\022>\n\013OfferDrinks\022\025.c" +
      "inema2.DrinkRequest\032\026.cinema2.DrinkRespo" +
      "nse0\001B%\n\020S05Drink_CatalogB\017S05DrinkCatal" +
      "ogP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_cinema2_DrinkRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cinema2_DrinkRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cinema2_DrinkRequest_descriptor,
        new java.lang.String[] { "DrinkIds", });
    internal_static_cinema2_DrinkResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_cinema2_DrinkResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cinema2_DrinkResponse_descriptor,
        new java.lang.String[] { "DrinkId", "ConfirmationMessage", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
