// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Method05.proto

package S05Drink_Catalog;

public final class S05DrinkCatalog {
  private S05DrinkCatalog() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_artifact_cinema_DrinkRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_artifact_cinema_DrinkRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_artifact_cinema_DrinkResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_artifact_cinema_DrinkResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016Method05.proto\022\017artifact_cinema\"!\n\014Dri" +
      "nkRequest\022\021\n\tdrink_ids\030\001 \003(\005\"?\n\rDrinkRes" +
      "ponse\022\020\n\010drink_id\030\001 \001(\005\022\034\n\024confirmation_" +
      "message\030\002 \001(\t2^\n\014DrinkService\022N\n\013OfferDr" +
      "inks\022\035.artifact_cinema.DrinkRequest\032\036.ar" +
      "tifact_cinema.DrinkResponse0\001B%\n\020S05Drin" +
      "k_CatalogB\017S05DrinkCatalogP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_artifact_cinema_DrinkRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_artifact_cinema_DrinkRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_artifact_cinema_DrinkRequest_descriptor,
        new java.lang.String[] { "DrinkIds", });
    internal_static_artifact_cinema_DrinkResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_artifact_cinema_DrinkResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_artifact_cinema_DrinkResponse_descriptor,
        new java.lang.String[] { "DrinkId", "ConfirmationMessage", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
