// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Method02.proto

package S02Seat_Water;

public interface ActivateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cinema2.ActivateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * User's choice to activate or deactivate the feature
   * </pre>
   *
   * <code>string choice = 1;</code>
   */
  java.lang.String getChoice();
  /**
   * <pre>
   * User's choice to activate or deactivate the feature
   * </pre>
   *
   * <code>string choice = 1;</code>
   */
  com.google.protobuf.ByteString
      getChoiceBytes();
}
