// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Method02.proto

package S02Seat_Water;

public interface ActivateResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cinema2.ActivateResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Message to inform the user about the change
   * </pre>
   *
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <pre>
   * Message to inform the user about the change
   * </pre>
   *
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
