// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Method02.proto

package S02Seat_Water;

public final class Serv02Seat_Water {
  private Serv02Seat_Water() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cinema2_ActivateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cinema2_ActivateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cinema2_ActivateResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cinema2_ActivateResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016Method02.proto\022\007cinema2\"!\n\017ActivateReq" +
      "uest\022\016\n\006choice\030\001 \001(\t\"#\n\020ActivateResponse" +
      "\022\017\n\007message\030\001 \001(\t2d\n\014S02SeatWater\022T\n\035Act" +
      "ivateWaterImmersiveFeature\022\030.cinema2.Act" +
      "ivateRequest\032\031.cinema2.ActivateResponseB" +
      "#\n\rS02Seat_WaterB\020Serv02Seat_WaterP\001b\006pr" +
      "oto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_cinema2_ActivateRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cinema2_ActivateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cinema2_ActivateRequest_descriptor,
        new java.lang.String[] { "Choice", });
    internal_static_cinema2_ActivateResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_cinema2_ActivateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cinema2_ActivateResponse_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
