// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Method03.proto

package S03Cinema_Lights;

public interface LightsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cinema2.LightsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Status message such as "Lights on" or "Lights off"
   * </pre>
   *
   * <code>string status = 1;</code>
   */
  java.lang.String getStatus();
  /**
   * <pre>
   * Status message such as "Lights on" or "Lights off"
   * </pre>
   *
   * <code>string status = 1;</code>
   */
  com.google.protobuf.ByteString
      getStatusBytes();
}
