// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Method01.proto

package S01Seat_Heating;

public final class Serv01Seat_Heating {
  private Serv01Seat_Heating() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cinema2_ActivateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cinema2_ActivateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cinema2_ActivateResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cinema2_ActivateResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016Method01.proto\022\007cinema2\"\037\n\017ActivateReq" +
      "uest\022\014\n\004name\030\001 \001(\t\"#\n\020ActivateResponse\022\017" +
      "\n\007message\030\001 \001(\t2[\n\017CinemaImmersive\022H\n\017Ac" +
      "tivateHeating\022\030.cinema2.ActivateRequest\032" +
      "\031.cinema2.ActivateResponse\"\000B\'\n\017S01Seat_" +
      "HeatingB\022Serv01Seat_HeatingP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_cinema2_ActivateRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cinema2_ActivateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cinema2_ActivateRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_cinema2_ActivateResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_cinema2_ActivateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cinema2_ActivateResponse_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
